FROM registry1.dso.mil/ironbank/google/distroless/java-11:nonroot

ARG BOOTSTRAP_SERVER=k8s-kafka
ARG TOPIC_NAME=k8s

EXPOSE 9092

COPY target/kafka-test-tool-0.10.0.jar /app/

COPY test-files/jsonObject.json /app/message.json

WORKDIR /app

CMD ["kafka-test-tool-0.10.0.jar",  "producer", "k8s-kafka:9092", "k8s", "-f",  "/app/message.json"]