version: '3'
services:
  zookeeper:
    container_name: zookeeper-test
    hostname: zookeeper-test
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      kafka_network:
        ipv4_address: 172.30.0.2
        aliases: 
          - zookeeper

  kafka:
    container_name: kafka-main
    hostname: kafka-main
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-main:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafka_network:
        ipv4_address: 172.30.0.3
        aliases:
          - kafka

  topic-init:
    container_name: topic-init
    hostname: topic-init
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    environment:
      TOPIC_NAME: ${TOPIC_NAME:-default-topic}
      BOOTSTRAP_SERVER: ${BOOTSTRAP_SERVER:-kafka-main:9092}
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 10 && kafka-topics --create --topic $TOPIC_NAME --bootstrap-server $BOOTSTRAP_SERVER --partitions 3 --replication-factor 1"]
    networks:
      kafka_network:
        ipv4_address: 172.30.0.4



networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

