version: '3'
services:
  zookeeper:
    container_name: k8s-zookeeper
    hostname: k8s-zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      k8s_network:
        ipv4_address: 172.50.0.2
        aliases: 
          - zookeeper

  kafka:
    container_name: k8s-kafka
    hostname: k8s-kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://k8s-test:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      k8s_network:
        ipv4_address: 172.50.0.3
        aliases:
          - kafka

  topic-init:
    container_name: topic-init
    hostname: topic-init
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    environment:
      TOPIC_NAME: ${TOPIC_NAME:-k8s}
      BOOTSTRAP_SERVER: ${BOOTSTRAP_SERVER:-k8s-kafka:9092}
    entrypoint: ["/bin/sh", "-c"]
    command: ["sleep 5 && kafka-topics --create --topic k8s --bootstrap-server k8s-kafka:9092 --partitions 3 --replication-factor 1"]
    networks:
      k8s_network:
        ipv4_address: 172.50.0.4

  producer:
    container_name: k8s_produce
    hostname: k8s_produce
    image: k8s_produce:0.10.0
    depends_on:
      - kafka
    networks:
      k8s_network:
        ipv4_address: 172.50.0.5

  consumer:
    container_name: k8s_consumer
    hostname: k8s_consumer
    image: k8s_consume:0.10.0
    depends_on:
      - kafka
    networks:
      k8s_network:
        ipv4_address: 172.50.0.6

networks:
  k8s_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16

