apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    io.kompose.service: producer
