apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: producer
  name: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: producer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f k8s-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: producer
    spec:
      containers:
        - image: k8s_produce:0.10.0
          name: k8s-produce
      hostname: k8s_produce
      restartPolicy: Always
